### ISSUE TITLE
NLogConfig sends double message to log

### ISSUE THREAD

**Issue by RichPruitt** [sschmid/Sherlog#1]
In the NLogConfig for Unity, if you have catchUnityLogs checked then the start method wires up to both

Application.logMessageReceivedThreaded += onLog;
Application.logMessageReceived += onLog;

Looks like that is causing double writes for each log message.

Here is notes from the unity docs:

"Note that it is not necessary to subscribe to both Application.logMessageReceived and Application.logMessageReceivedThreaded. The multi-threaded variant will also be called for messages on the main thread."

**Comment by fingerx** [comment]
@RichPruitt  this great！thanks.

**Comment by sschmid** [comment]
Will close, Unity appenders have been removed.
See #3
